site_name: 蟒营® 作曲启蒙原型班
site_description: 蟒营®系列 Pythonic 实训课程
site_author: guru101camp@googlegroups.com
site_url: https://mu.101.camp/
repo_url: https://github.com/101camp/mu
repo_name: github
copyright: ©101camp 2018-2020 


#theme:
#  font: false
#  logo: http://101.zoomquiet.top/res/icon/101camp_bauhaus_v3h32.png
#  favicon: /img/101camp_bauhaus_v4h420.ico
#  name: 'windmill-dark'
#  custom_dir: '_theme/material'
#theme:
#    name: null
#    font: false
#    logo: http://101.zoomquiet.top/res/icon/101camp_bauhaus_v3h32.png
#    favicon: /img/101camp_bauhaus_v4h420.ico
#    custom_dir: '_theme/mkdocs_windmill_dark'
#theme:
#  name: mkdocs
#  navigation_depth: 2
#  font: false
#  logo: http://101.zoomquiet.top/res/icon/101camp_bauhaus_v3h32.png
#  favicon: /img/101camp_bauhaus_v4h420.ico
#  custom_dir: _theme/mkdocs
theme: 
  name: 'cerulean'
  custom_dir: '_theme/bootswatch/cerulean'
  font: false
  logo: http://101.zoomquiet.top/res/icon/101camp_bauhaus_v3h32.png
  favicon: /img/101camp_bauhaus_v4h420.ico


markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true


plugins: []

nav:
    - Home: index.md
    - FAQ: faq.md
    - '过程': 
      #- '预备': process/0_prepare.md
      - '报名': process/1_signup.md
      - '进入': process/2_enter.md
      - '行进': process/3_running.md
      - '结束': process/4_restart.md
    - '故事': 
      - 'echo': story/students.md
    - '有关': 
      - '作品': about/works.md
      #- '关于': about/readme.md
      - '商标': about/brand.md
      #- '资源': about/resource.md
      - '许可': about/license.md



